name: 'Upstream Sync'

on:
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:
    inputs:
      sync_test_mode:
        description: 'Fork Sync Test Mode'
        type: boolean
        default: false

jobs:
  sync_latest_from_upstream:
    runs-on: ubuntu-24.04
    name: Sync latest commits from upstream repo
    steps:
    -
      uses: actions/checkout@v4
      with:
        ref: staging
    -
      name: Sync upstream changes
      id: sync
      uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.1
      with:
        target_sync_branch: staging
        target_repo_token: ${{ github.token }}
        upstream_sync_branch: staging
        upstream_sync_repo: SillyTavern/SillyTavern
        test_mode: ${{ inputs.sync_test_mode }}
    -
      name: New commits found
      if: steps.sync.outputs.has_new_commits == 'true'
      run: echo "New commits were found to sync."
    -
      name: No new commits
      if: steps.sync.outputs.has_new_commits == 'false'
      run: echo "There were no new commits."
    -
      name: Show value of 'has_new_commits'
      run: echo ${{ steps.sync.outputs.has_new_commits }}
    -
      uses: Mattraks/delete-workflow-runs@v2
      with:
        token: ${{ github.token }}
        repository: ${{ github.repository }}
        retain_days: 0
        keep_minimum_runs: 0
