name: keepalive
on:
  schedule:
    - cron: "0 0 1 * *"
permissions:
  actions: write
jobs:
  keepalive:
    name: keepalive
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@v2